[package]
name = "web_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking"] }
scraper = "0.20"
csv = "1.3.0"
tokio = { version = "1", features = ["full"] }            # for async reqwest
